### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by shad0w0sec** [z92g/ZentaoSqli#2]

**Comment by z92g** [comment]
都是根据随机md5值取判断的，应该不存在，可以看下源代码

**Comment by Aesthetican** [comment]
不好意思刚才是我手工测试的时候发送包搞错了,但是我测试时有回显,没有md5加密值
![image](https://user-images.githubusercontent.com/73059812/193450287-d89a0352-a479-4376-b6b8-674524055502.png)
